Feat#4_1 [게시글 작성] 페이지 생성
FRONTENDSCHOOL7/final-14-Deskoration pull request #14
Opened 2023-10-24 06:22 UTC by jungmin801

## 작업사항
1.  게시글 작성 페이지 레이아웃 구현
2. 이미지 마커 드래그 앤 드롭 기능
3. 상품 정보 등록하기 
4. 필수 input 필드 유효성 검사

### 코멘트 해주세요
- [ ] 이미지 마커 작동에 오류가 있는지 살펴주세요 
- [ ] 필수 input 필드 유효성 검사에 오류가 있는지 살펴주세요

2023-10-24 13:08 UTC, Herrypi commented
넵~! 다 확인한 후 이상없이 작동하였습니다!

2023-10-25 00:12 UTC, Herrypi requested changes
오류인 부분만 수정하면 될 것 같습니다!

2023-10-25 00:23 UTC, jungmin801 commented on src/pages/NewBoard/RegisterForm.jsx
> +    // 유효성 검사 함수
현재는 각 input 필드에서 포커스를 잃을 때마다 유효성 검사를 하도록 구현을 했는데 제대로 작동을 안하네요. 그래서 submit버튼을 눌렀을 때 한번에 유효성 검사를 진행하도록 코드를 변경하려고 합니다.

2023-10-25 00:26 UTC, jungmin801 commented on src/pages/NewBoard/PostUpload.jsx
> +                        items.map((item, index) => (
마커가 하단에 있는 삭제, 되돌리기 버튼 영역으로 들어가면 겹치면서 작동이 안되는 것 같습니다. 확인해보겠습니다.

2023-10-25 04:53 UTC, jungmin801 commented on src/pages/NewBoard/RegisterForm.jsx
> +    // 유효성 검사 함수
코드 수정했습니다!! 확인부탁드려요!

2023-10-25 04:54 UTC, jungmin801 commented on src/pages/NewBoard/PostUpload.jsx
> +                        items.map((item, index) => (
마커에 z-index를 주어 수정했습니다. 이미지 위에 뜨는 버튼들과 겹쳐도 잘 작동하는지 확인 한번 부탁드려요!!

2023-10-25 07:45 UTC, merged