Feat#3 1 [홈화면] 페이지 생성
FRONTENDSCHOOL7/final-14-Deskoration pull request #16
Opened 2023-10-24 08:24 UTC by wooluck210

## 작업사항
1. 홈화면 페이지 생성
2. 헤더 컴포넌트 구현
3. 게시물 클릭시 Board로 이동
4. 게시물 섹션 무한 스크롤

### 코멘트
- [ ] 홈화면 페이지에서 구현하지 않은 부분이 있는지 확인해주세요
- [ ] UI에서 수정할 부분 확인해주세요.
- [ ] 어떤 코멘트든 좋습니다..!

2023-10-24 13:20 UTC, jungmin801 commented
준하님 고생하셨습니다!!
작동에 크게 오류가 나는 부분은 없어보입니다. 무한 스크롤도 잘 되네요!
약간 수정이 필요한 부분과 UI 관련 질문을 아래에 정리해봤습니다. 확인 부탁드려요~! 

1. article컴포넌트에서 map 메서드 사용 시에 key prop을 입력하라는 에러가 나옵니다! 수정 부탁드립니다!

2. slide에서 아이템에 마진을 고정값으로 설정하는 것 보다는 반응형으로 고려해서 flex를 이용해서 gap을 주거나 justify-content:between 같은걸 쓰면 어떨까요?

3. slide item에 카테고리명이 들어가는 부분을 span이나 p태그로 하지 않고, after 가상요소를 주신 이유가 있나요?

2023-10-24 14:25 UTC, jungmin801 requested changes
리뷰 완료입니다! 체크 부탁드려요!

2023-10-25 02:10 UTC, wooluck210 commented on src/pages/Home/Slide.styled.jsx
> +    margin: 0 15px 20px 0;
반응형을 위해서 더 좋은 방법인 거 같네요. 반영했습니다!

2023-10-25 08:03 UTC, wooluck210 commented on src/pages/Home/Article.jsx
> +                {articles.map((article, index) => (
index로 임시로 key 값을 주어 해결 했습니다. map 함수의 key 값을 index로 부여하는 것은 지양해야 하지만 기능 구현부터 하고 나서 추후에 수정해보려고 합니다.

2023-10-25 08:05 UTC, wooluck210 commented on src/pages/Home/Slide.styled.jsx
> +    &::after {
마크업을 줄이려고 가상요소를 사용했는데 category명을 입력해야 해서 p 태그로 수정하고, 카테고리 개수에 맞춰 스크롤 설정도 했습니다.

2023-10-25 08:13 UTC, jungmin801 commented on src/pages/Home/Slide.styled.jsx
> +    &::after {
확인했습니다! 고생하셨어요!

2023-10-25 08:13 UTC, jungmin801 approved these changes

2023-10-25 08:18 UTC, merged