Refactor/followPage#237
FRONTENDSCHOOL7/final-14-Deskoration pull request #248
Opened 2023-12-29 08:38 UTC by wooluck210

## 작업사항
계정-유저 팔로우, 팔로잉 리스트 코드 개선

### 코멘트
- [ ] 프로필 팔로우, 팔로잉 리스트가 잘 호출되는지 확인해주세요.
- [ ] 유저 프로필 팔로우, 팔로잉 리스트가 잘 호출되는지 확인해주세요.

#### 기타
분리되었다가 합쳐진 팔로우, 팔로잉 리스트 코드 확인하고 궁금한 점이나 개선점 있으면 말씀해주세요.

2023-12-30 14:15 UTC, jungmin801 requested changes
준하님 고생하셨습니다! 메세지 부분은 코드에 직접 코멘트를 달았는데, 추가로 두 가지 더 전달드릴 사항이 있습니다.

1. 상대 프로필에서 팔로우를 하면 팔로우가 되는데, 언팔로우를 하면 작동이 안됩니다. 버튼도 안바뀌고 언팔로우도 되지 않아요(페이지를 나갔다 들어와도 동일).
2. isLoading일때 Loading.. 이라고 잠깐 뜨는데, 차라리 로더 컴포넌트를 보여주는게 낫지 않을까 싶습니다.

이부분 확인 부탁드립니다!!

2023-12-30 14:15 UTC, jungmin801 commented on src/pages/FollowFollowingList/FollowingList.jsx
> +                    btnLabel={'홈으로 돌아가기'}
이건 개인적인 의견인데, 팔로워와 팔로잉이 좀 헷갈려서
mainTxt가 조금 구분이 되면 어떨까 싶어요

예를들어, 팔로워 페이지에서는 '아직 팔로우 중인 유저가 없습니다!' / 팔로잉 페이지에서는 '아직 나를 팔로우하는 유저가 없습니다!' 이런식으로 구분을 주면 어떨까요??

그리고 subTxt에서는 ! 빼고 . 으로 가는게 좋을거 같아요~

2023-12-31 07:37 UTC, wooluck210 commented on src/pages/FollowFollowingList/FollowingList.jsx
> +                    btnLabel={'홈으로 돌아가기'}
안내 문구 추천 감사합니다! 추천해주신 문구가 더 자연스럽고 이해가 잘 되는 거 같아요!
문자부호도 반영하도록 하겠습니다~

2023-12-31 07:51 UTC, wooluck210 commented
1. 상대 프로필에서 언팔로우 작동하도록 수정했습니다.
2. 로더 컴포넌트를 적용했습니다.
확인 부탁드립니다!

2023-12-31 14:47 UTC, jungmin801 approved these changes

2023-12-31 14:47 UTC, merged