Feat#10_1 [ChatRoomPage] 채팅페이지 구현
FRONTENDSCHOOL7/final-14-Deskoration pull request #29
Opened 2023-10-26 09:14 UTC by Herrypi

##작업사항
1. 채팅방 리스트 페이지와 채팅창 페이지 연결
2. 해당채팅방 클릭 시 해당하는 채팅창으로 이동
3. 채팅 전송 기능
4. 스크롤 하단으로 고정
5. 상대 채팅과 자신의 채팅 좌우 배치->채팅 구분을 위해

###코멘트
- [ ] UI적으로 문제는 없는지 수정할 부분을 남겨주세요
- [ ] 채팅 전송 기능에 문제는 없는지 확인 부탁드려요
- [ ] 아래에 제공한 App.js 코드를 넣은 상태로 채팅방 이동이 잘 되는지 확인 부탁드려요

###기타
코드 리뷰시 App.js 코드를 아래 코드로 대체 한 후 실행 해주세요
```
import { ThemeProvider } from 'styled-components';
import GlobalStyle from './styles/GlobalStyle';
import theme from './styles/theme';

// 추후 라우터 설정하면 라우터에 css적용할 예정입니다.
import './App.css';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import ChatListPage from './pages/Chat/ChatListPage/ChatListPage';
import ChatRoomPage from './pages/Chat/ChatRoomPage/ChatRoomPage';
function App() {
    return (
        <div className="app-body">
            <div className="container">
                <ThemeProvider theme={theme}>
                    <GlobalStyle />
                    <BrowserRouter>
                        <Routes>
                            <Route path="/chat" element={<ChatListPage />} />
                            <Route
                                path="/chat/:username"
                                element={<ChatRoomPage />}
                            />
                        </Routes>
                    </BrowserRouter>
                </ThemeProvider>
            </div>
        </div>
    );
}

export default App;

```

2023-10-26 10:56 UTC, YennieJ requested changes
현진님 스크롤을 커스텀 하셨군요👍

1. UI
- [x] 마지막 메세지 border-bottom은 없어도 좋을것 같습니다.
- [x] 스크롤이 좀 더 오른쪽으로 이동하면 좋을꺼같아요.
2. 채팅 전송 기능 잘돼요!
3. 채팅방 이동
- [x] 채팅방 이동이 잘되는데 뒤로가기 이모티콘을 눌렀을 때도 뒤로 돌아갔으면 좋겠습니다!
- [x] 채팅방 이동시 콘솔에 warning이 뜹니다. 수정 부탁드려요

2023-10-26 14:05 UTC, wooluck210 approved these changes
전체적인 의견은 예진님과 비슷합니다. 콘솔 에러는 한번 찾아봤어요!

2023-10-26 14:05 UTC, wooluck210 commented on src/pages/Chat/ChatRoomPage/ChatRoomPage.jsx
> +                        <S.ChatContent key={index} isSentByUser={false}>
isSentByUser를 스타일 컴포넌트에서 prop으로 받으면서 대문자로 생기는 오류가 콘솔창에 뜹니다. 소문자로 바꾸면 문제가 해결될 거 같아요.
저도 스크롤이 홈화면에서 너무 크게 잡아먹고 디자인도 별로인 것이 고민인데, 같이 찾아보면 좋을 거 같습니다.

2023-10-28 08:25 UTC, Herrypi commented on src/pages/Chat/ChatRoomPage/ChatRoomPage.jsx
> +                        <S.ChatContent key={index} isSentByUser={false}>
넵! 피드백 적용 해서 다시 푸쉬 했습니다! 다시한번 확인 부탁드려요~!!

2023-10-29 15:51 UTC, YennieJ approved these changes

2023-10-29 15:52 UTC, YennieJ approved these changes
수정 완벽👍 고생하셨습니다!

2023-10-29 16:41 UTC, Herrypi reviewed
완료했습니다!

2023-10-29 18:54 UTC, merged