Feat#3_1 [홈화면 수정] 홈화면에 푸터 적용 및 UI 수정
FRONTENDSCHOOL7/final-14-Deskoration pull request #31
Opened 2023-10-27 06:56 UTC by wooluck210

본문:
## 작업사항
1. 정민님 푸터 적용 및 그에 따른 UI 수정

### 코멘트해주세요.
- [ ] UI에서 여백이나 로고, 아이콘 크기가 적절한지
- [ ] 그 외 무엇이든 좋습니다.

2023-10-27 14:11 UTC, jungmin801 requested changes
홈에 무한스크롤과 슬라이드가 들어가다보니 UI도 쉽지 않군요 ㅠㅠ 고생 많으셨습니다!!!
제가 슬라이드 컴포넌트 코드를 조금 변경해보았는데, 참고해서 살짝 고쳐주시면 더 좋을 것 같아요 감사합니다! 👍

2023-10-27 14:11 UTC, jungmin801 commented on src/pages/Home/Slide.jsx
>                  </S.Category>
마크업과 스타일을 조금 변경해보면 어떨까요? 시맨틱하진 않긴하지만ㅠㅠ 저라면 이렇게 해볼 것 같아요!
```jsx
<div>
    <S.Category $url={Img}></S.Category>
    <S.CateName>책상</S.CateName>
</div>
```

2023-10-27 14:11 UTC, jungmin801 commented on src/pages/Home/Slide.styled.jsx
> +    margin: 10px 25px;
헤더와 해당 섹션이 마진 병합 현상(이름 정확하지 않아요ㅠㅠ)이 발생해서 마진이 아니라 패딩을 넣으면 좋을 것 같습니다!

2023-10-27 14:11 UTC, jungmin801 commented on src/pages/Home/Slide.styled.jsx
>  `;
만약 제가 제안드린 마크업을 적용한다면, 스타일을 이런 식으로 가져가면 좋을 것 같아요! 이미지 url을 프롭스로 받아오면 각각 다른 이미지들이 들어갈 수 있을 것 같습니다!

```jsx
export const Category = styled.div`
    color: ${theme.subFont};
    width: 50px;
    height: 50px;
    border: 1px solid black;
    border-radius: 50%;
    margin-bottom: 5px;

    // 혹시 단축속성을 아신다면 아래는 합치셔도 될 것 같아요! 제가 단축속성을 잘 몰라서요 ㅠㅠ
    background-image: url(${({ $url }) => $url});
    background-size: 100% 100%;
    background-position: 50% 50%;
    background-repeat: no-repeat;
`;
```

2023-10-29 11:00 UTC, wooluck210 commented on src/pages/Home/Slide.styled.jsx
> +    margin: 10px 25px;
마진 병합 현상을 의도한 것은 아니었지만, 헤더와 섹션 컴포넌트 간격이 20px보다는 10px인게 좀 더 나아보여서 일단 수정하지 않겠습니다. 이 부분은 팀원들이랑 상의해볼게요!

2023-10-29 11:40 UTC, wooluck210 commented on src/pages/Home/Slide.styled.jsx
>  `;
위에서 제시해주신 마크업과 스타일을 적용해보았어요. 제가 만들었던 것보다 시맨틱한 것 같아서 반영하려고 합니다! 의도하신 것과 다른 부분이 있으면 말씀해주세요.

2023-10-29 11:41 UTC, wooluck210 commented on src/pages/Home/Slide.jsx
>                  </S.Category>
아래 스타일과 함께 답변 드리겠습니다!

2023-10-31 01:14 UTC, jungmin801 commented on src/pages/Home/Slide.styled.jsx
>  `;
준하님 확인했습니다! 아주 좋습니다!!
한 가지 저도 방금 생각이 났는데, 슬라이드의 각 요소가 지금 div로 묶여있는데 기능을 생각해보니 얘들이 버튼이 되어야 하겠네요. 이 부분은 추후에 이미지 넣으면서 변경하면 될 것 같습니다. 
고생하셨습니다~!!

2023-10-31 01:15 UTC, jungmin801 approved these changes

2023-10-31 01:27 UTC, wooluck210 commented on src/pages/Home/Slide.styled.jsx
>  `;
넵 추후에 버튼 요소로 수정하도록 하겠습니다!

2023-10-31 01:46 UTC, merged